name: "Test typescript-action"
on:
  pull_request: [syncronize, created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm run build
    - uses: ./
      with: 
        build-script: npm run build
